# Generated by Django 3.0.2 on 2020-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201020_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cart_order', 'Cart_order'), ('Not confirmed', 'Not confirmed'), ('Called', 'Called'), ('Payed', 'Payed'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Cart_order', max_length=200),
        ),
    ]
