# Generated by Django 3.0.3 on 2020-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201027_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cart_order', 'Cart_order'), ('Не підтверджений', 'Not confirmed'), ('Підтверджений', 'Called'), ('Оплачений', 'Payed'), ('Відправлений', 'Sent'), ('Виконаний', 'Delivered'), ('Скасований', 'Canceled')], default='Cart_order', max_length=200),
        ),
    ]
