# Generated by Django 3.0.3 on 2020-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201211_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In stock', 'В наявності'), ('Not available', 'Нема в наявності')], default='In stock', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
