# Generated by Django 3.0.3 on 2020-12-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201211_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='stock',
        ),
    ]
